
name: check Awesome Search resources

on:
  workflow_dispatch:

jobs:
  check-links:
    name: check links for 404
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
